# Generated by Django 6.0.3 on 2026-05-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_market_data_postgres'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBasicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts_code', models.CharField(db_index=True, max_length=24)),
                ('field_name', models.CharField(db_index=True, max_length=80)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('source_date', models.CharField(blank=True, default='', max_length=8)),
                ('raw_record', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'tushare_stock_basic_history',
            },
        ),
        migrations.RenameIndex(
            model_name='dailybasic',
            new_name='tushare_sto_trade_d_8b2ca2_idx',
            old_name='tushare_sto_trade__8bcc1e_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyquote',
            new_name='tushare_sto_trade_d_07600b_idx',
            old_name='tushare_sto_trade__475249_idx',
        ),
        migrations.RenameIndex(
            model_name='tradecal',
            new_name='tushare_tra_is_open_69e389_idx',
            old_name='tushare_tra_is_open_c53b8b_idx',
        ),
        migrations.AddField(
            model_name='stockbasic',
            name='act_ent_type',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='stockbasic',
            name='act_name',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='stockbasic',
            name='cnspell',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='stockbasic',
            name='curr_type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='stockbasic',
            name='delist_date',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='stockbasic',
            name='enname',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='stockbasic',
            name='exchange',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='stockbasic',
            name='fullname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stockbasic',
            name='list_status',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
        migrations.AddIndex(
            model_name='stockbasichistory',
            index=models.Index(fields=['ts_code', 'created_at'], name='tushare_sto_ts_code_6776b2_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbasichistory',
            index=models.Index(fields=['field_name', 'created_at'], name='tushare_sto_field_n_a59da6_idx'),
        ),
    ]
