# Generated by Django 6.0.3 on 2026-05-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stockbasichistory_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='tradecal',
            table_comment='TuShare交易日历',
        ),
        migrations.AlterField(
            model_name='tradecal',
            name='cal_date',
            field=models.CharField(db_comment='日历日期 YYYYMMDD', max_length=8, verbose_name='日历日期'),
        ),
        migrations.AlterField(
            model_name='tradecal',
            name='exchange',
            field=models.CharField(db_comment='交易所 SSE上交所 SZSE深交所', max_length=16, verbose_name='交易所'),
        ),
        migrations.AlterField(
            model_name='tradecal',
            name='is_open',
            field=models.IntegerField(blank=True, db_comment='是否交易 0休市 1交易', db_index=True, null=True, verbose_name='是否交易'),
        ),
        migrations.AlterField(
            model_name='tradecal',
            name='pretrade_date',
            field=models.CharField(blank=True, db_comment='上一交易日 YYYYMMDD', max_length=8, null=True, verbose_name='上一交易日'),
        ),
        migrations.AlterField(
            model_name='tradecal',
            name='tushare_meta',
            field=models.JSONField(blank=True, db_comment='TuShare分类、接口和目标表元数据', default=dict, verbose_name='TuShare元数据'),
        ),
        migrations.CreateModel(
            name='StockCapitalPremarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade_date', models.CharField(db_comment='交易日期 YYYYMMDD', max_length=8, verbose_name='交易日期')),
                ('ts_code', models.CharField(db_comment='TuShare股票代码', max_length=24, verbose_name='TS股票代码')),
                ('total_share', models.FloatField(blank=True, db_comment='总股本 万股', null=True, verbose_name='总股本')),
                ('float_share', models.FloatField(blank=True, db_comment='流通股本 万股', null=True, verbose_name='流通股本')),
                ('pre_close', models.FloatField(blank=True, db_comment='昨收价', null=True, verbose_name='昨收价')),
                ('up_limit', models.FloatField(blank=True, db_comment='涨停价', null=True, verbose_name='涨停价')),
                ('down_limit', models.FloatField(blank=True, db_comment='跌停价', null=True, verbose_name='跌停价')),
                ('tushare_meta', models.JSONField(blank=True, db_comment='TuShare分类、接口和目标表元数据', default=dict, verbose_name='TuShare元数据')),
            ],
            options={
                'db_table': 'tushare_stk_premarket',
                'db_table_comment': 'TuShare股本情况盘前',
                'indexes': [models.Index(fields=['trade_date', 'ts_code'], name='tushare_stk_trade_d_e7085b_idx'), models.Index(fields=['ts_code', 'trade_date'], name='tushare_stk_ts_code_c39539_idx')],
                'constraints': [models.UniqueConstraint(fields=('ts_code', 'trade_date'), name='uniq_stk_premarket_ts_code_date')],
            },
        ),
        migrations.CreateModel(
            name='StockCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts_code', models.CharField(db_comment='TuShare股票代码', max_length=24, unique=True, verbose_name='TS股票代码')),
                ('com_name', models.CharField(blank=True, db_comment='公司全称', db_index=True, max_length=240, null=True, verbose_name='公司全称')),
                ('com_id', models.CharField(blank=True, db_comment='统一社会信用代码', db_index=True, max_length=64, null=True, verbose_name='统一社会信用代码')),
                ('exchange', models.CharField(blank=True, db_comment='交易所代码', db_index=True, max_length=16, null=True, verbose_name='交易所代码')),
                ('chairman', models.CharField(blank=True, db_comment='法人代表', max_length=80, null=True, verbose_name='法人代表')),
                ('manager', models.CharField(blank=True, db_comment='总经理', max_length=80, null=True, verbose_name='总经理')),
                ('secretary', models.CharField(blank=True, db_comment='董事会秘书', max_length=80, null=True, verbose_name='董秘')),
                ('reg_capital', models.FloatField(blank=True, db_comment='注册资本 万元', null=True, verbose_name='注册资本')),
                ('setup_date', models.CharField(blank=True, db_comment='注册日期 YYYYMMDD', db_index=True, max_length=8, null=True, verbose_name='注册日期')),
                ('province', models.CharField(blank=True, db_comment='所在省份', max_length=80, null=True, verbose_name='所在省份')),
                ('city', models.CharField(blank=True, db_comment='所在城市', max_length=80, null=True, verbose_name='所在城市')),
                ('introduction', models.TextField(blank=True, db_comment='公司介绍', null=True, verbose_name='公司介绍')),
                ('website', models.CharField(blank=True, db_comment='公司主页', max_length=240, null=True, verbose_name='公司主页')),
                ('email', models.CharField(blank=True, db_comment='电子邮件', max_length=160, null=True, verbose_name='电子邮件')),
                ('office', models.CharField(blank=True, db_comment='办公室地址', max_length=300, null=True, verbose_name='办公室')),
                ('employees', models.IntegerField(blank=True, db_comment='员工人数', null=True, verbose_name='员工人数')),
                ('main_business', models.TextField(blank=True, db_comment='主要业务及产品', null=True, verbose_name='主要业务及产品')),
                ('business_scope', models.TextField(blank=True, db_comment='经营范围', null=True, verbose_name='经营范围')),
                ('tushare_meta', models.JSONField(blank=True, db_comment='TuShare分类、接口和目标表元数据', default=dict, verbose_name='TuShare元数据')),
            ],
            options={
                'db_table': 'tushare_stock_company',
                'db_table_comment': 'TuShare上市公司基本信息',
                'indexes': [models.Index(fields=['exchange', 'ts_code'], name='tushare_sto_exchang_335f2f_idx'), models.Index(fields=['province', 'city'], name='tushare_sto_provinc_6d4a7a_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockHsgt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts_code', models.CharField(db_comment='TuShare股票代码', max_length=24, verbose_name='TS股票代码')),
                ('trade_date', models.CharField(db_comment='交易日期 YYYYMMDD', max_length=8, verbose_name='交易日期')),
                ('type', models.CharField(db_comment='沪深港通类型', db_index=True, max_length=16, verbose_name='港股通类型')),
                ('name', models.CharField(blank=True, db_comment='股票名称', max_length=80, null=True, verbose_name='股票名称')),
                ('type_name', models.CharField(blank=True, db_comment='沪深港通类型名称', max_length=80, null=True, verbose_name='港股通类型名称')),
                ('tushare_meta', models.JSONField(blank=True, db_comment='TuShare分类、接口和目标表元数据', default=dict, verbose_name='TuShare元数据')),
            ],
            options={
                'db_table': 'tushare_stock_hsgt',
                'db_table_comment': 'TuShare沪深港通股票列表',
                'indexes': [models.Index(fields=['trade_date', 'type'], name='tushare_sto_trade_d_63c95b_idx'), models.Index(fields=['ts_code', 'trade_date'], name='tushare_sto_ts_code_f7daf9_idx')],
                'constraints': [models.UniqueConstraint(fields=('ts_code', 'trade_date', 'type'), name='uniq_stock_hsgt_code_date_type')],
            },
        ),
        migrations.CreateModel(
            name='StockNameChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts_code', models.CharField(db_comment='TuShare股票代码', max_length=24, verbose_name='TS股票代码')),
                ('name', models.CharField(db_comment='证券名称', max_length=80, verbose_name='证券名称')),
                ('start_date', models.CharField(blank=True, db_comment='开始日期 YYYYMMDD', db_index=True, max_length=8, null=True, verbose_name='开始日期')),
                ('end_date', models.CharField(blank=True, db_comment='结束日期 YYYYMMDD', db_index=True, max_length=8, null=True, verbose_name='结束日期')),
                ('ann_date', models.CharField(blank=True, db_comment='公告日期 YYYYMMDD', db_index=True, max_length=8, null=True, verbose_name='公告日期')),
                ('change_reason', models.CharField(blank=True, db_comment='变更原因', max_length=200, null=True, verbose_name='变更原因')),
                ('tushare_meta', models.JSONField(blank=True, db_comment='TuShare分类、接口和目标表元数据', default=dict, verbose_name='TuShare元数据')),
            ],
            options={
                'db_table': 'tushare_stock_namechange',
                'db_table_comment': 'TuShare股票曾用名',
                'indexes': [models.Index(fields=['ts_code', 'start_date'], name='tushare_sto_ts_code_14bc10_idx'), models.Index(fields=['ann_date', 'ts_code'], name='tushare_sto_ann_dat_1c7378_idx')],
                'constraints': [models.UniqueConstraint(fields=('ts_code', 'name', 'start_date'), name='uniq_namechange_code_name_start')],
            },
        ),
        migrations.CreateModel(
            name='StockSTList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts_code', models.CharField(db_comment='TuShare股票代码', max_length=24, verbose_name='TS股票代码')),
                ('name', models.CharField(blank=True, db_comment='股票名称', max_length=80, null=True, verbose_name='股票名称')),
                ('trade_date', models.CharField(db_comment='交易日期 YYYYMMDD', max_length=8, verbose_name='交易日期')),
                ('type', models.CharField(blank=True, db_comment='风险警示类型代码', db_index=True, max_length=16, null=True, verbose_name='风险类型')),
                ('type_name', models.CharField(blank=True, db_comment='风险警示类型名称', max_length=80, null=True, verbose_name='风险类型名称')),
                ('tushare_meta', models.JSONField(blank=True, db_comment='TuShare分类、接口和目标表元数据', default=dict, verbose_name='TuShare元数据')),
            ],
            options={
                'db_table': 'tushare_stock_st',
                'db_table_comment': 'TuShare ST股票列表',
                'indexes': [models.Index(fields=['trade_date', 'type'], name='tushare_sto_trade_d_8d680c_idx'), models.Index(fields=['ts_code', 'trade_date'], name='tushare_sto_ts_code_3c7069_idx')],
                'constraints': [models.UniqueConstraint(fields=('ts_code', 'trade_date', 'type'), name='uniq_stock_st_code_date_type')],
            },
        ),
        migrations.CreateModel(
            name='StockSTRiskNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts_code', models.CharField(db_comment='TuShare股票代码', max_length=24, verbose_name='TS股票代码')),
                ('name', models.CharField(blank=True, db_comment='股票名称', max_length=80, null=True, verbose_name='股票名称')),
                ('pub_date', models.CharField(db_comment='公告日期 YYYYMMDD', max_length=8, verbose_name='公告日期')),
                ('imp_date', models.CharField(blank=True, db_comment='实施日期 YYYYMMDD', db_index=True, max_length=8, null=True, verbose_name='实施日期')),
                ('st_tpye', models.CharField(blank=True, db_comment='TuShare接口字段名为st_tpye', max_length=40, null=True, verbose_name='ST类型')),
                ('st_reason', models.TextField(blank=True, db_comment='风险警示原因', null=True, verbose_name='ST原因')),
                ('st_explain', models.TextField(blank=True, db_comment='风险警示说明', null=True, verbose_name='ST说明')),
                ('tushare_meta', models.JSONField(blank=True, db_comment='TuShare分类、接口和目标表元数据', default=dict, verbose_name='TuShare元数据')),
            ],
            options={
                'db_table': 'tushare_st_risk_notice',
                'db_table_comment': 'TuShare ST风险警示板股票',
                'indexes': [models.Index(fields=['pub_date', 'ts_code'], name='tushare_st__pub_dat_5b0bfe_idx'), models.Index(fields=['ts_code', 'imp_date'], name='tushare_st__ts_code_88ad29_idx')],
                'constraints': [models.UniqueConstraint(fields=('ts_code', 'pub_date', 'st_tpye'), name='uniq_st_risk_code_pub_type')],
            },
        ),
    ]
