# Generated by Django 6.0.3 on 2026-05-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tradecal_table_comment_alter_tradecal_cal_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='stockbasic',
            table_comment='TuShare股票基础信息',
        ),
        migrations.AlterModelTableComment(
            name='stockbasichistory',
            table_comment='TuShare股票基础信息变更历史',
        ),
        migrations.RenameIndex(
            model_name='stockbasichistory',
            new_name='ix_stkbh_code_created',
            old_name='tushare_sto_ts_code_6776b2_idx',
        ),
        migrations.RenameIndex(
            model_name='stockbasichistory',
            new_name='ix_stkbh_field_created',
            old_name='tushare_sto_field_n_a59da6_idx',
        ),
        migrations.AlterField(
            model_name='stockbasic',
            name='act_ent_type',
            field=models.CharField(blank=True, db_comment='实控人企业性质', max_length=80, null=True, verbose_name='实控人企业性质'),
        ),
        migrations.AlterField(
            model_name='stockbasic',
            name='act_name',
            field=models.CharField(blank=True, db_comment='实控人名称', max_length=160, null=True, verbose_name='实控人名称'),
        ),
        migrations.AlterField(
            model_name='stockbasic',
            name='area',
            field=models.CharField(blank=True, db_comment='地域', max_length=80, null=True, verbose_name='地域'),
        ),
        migrations.AlterField(
            model_name='stockbasic',
            name='cnspell',
            field=models.CharField(blank=True, db_comment='拼音缩写', max_length=80, null=True, verbose_name='拼音缩写'),
        ),
        migrations.AlterField(
            model_name='stockbasic',
            name='curr_type',
            field=models.CharField(blank=True, db_comment='交易货币', max_length=16, null=True, verbose_name='交易货币'),
        ),
        migrations.AlterField(
            model_name='stockbasic',
            name='delist_date',
            field=models.CharField(blank=True, db_comment='退市日期 YYYYMMDD', max_length=8, null=True, verbose_name='退市日期'),
        ),
        migrations.AlterField(
            model_name='stockbasic',
            name='enname',
            field=models.CharField(blank=True, db_comment='英文全称', max_length=240, null=True, verbose_name='英文全称'),
        ),
        migrations.AlterField(
            model_name='stockbasic',
            name='exchange',
            field=models.CharField(blank=True, db_comment='交易所代码', max_length=16, null=True, verbose_name='交易所代码'),
        ),
        migrations.AlterField(
            model_name='stockbasic',
            name='fullname',
            field=models.CharField(blank=True, db_comment='股票全称', max_length=200, null=True, verbose_name='股票全称'),
        ),
        migrations.AlterField(
            model_name='stockbasic',
            name='industry',
            field=models.CharField(blank=True, db_comment='所属行业', max_length=120, null=True, verbose_name='所属行业'),
        ),
        migrations.AlterField(
            model_name='stockbasic',
            name='is_hs',
            field=models.CharField(blank=True, db_comment='是否沪深港通标的 N否 H沪股通 S深股通', max_length=8, null=True, verbose_name='是否沪深港通标的'),
        ),
        migrations.AlterField(
            model_name='stockbasic',
            name='list_date',
            field=models.CharField(blank=True, db_comment='上市日期 YYYYMMDD', max_length=8, null=True, verbose_name='上市日期'),
        ),
        migrations.AlterField(
            model_name='stockbasic',
            name='list_status',
            field=models.CharField(blank=True, db_comment='上市状态 L上市 D退市 P暂停上市 G其他', db_index=True, max_length=8, null=True, verbose_name='上市状态'),
        ),
        migrations.AlterField(
            model_name='stockbasic',
            name='market',
            field=models.CharField(blank=True, db_comment='市场类型', max_length=40, null=True, verbose_name='市场类型'),
        ),
        migrations.AlterField(
            model_name='stockbasic',
            name='name',
            field=models.CharField(blank=True, db_comment='股票名称', db_index=True, max_length=80, null=True, verbose_name='股票名称'),
        ),
        migrations.AlterField(
            model_name='stockbasic',
            name='symbol',
            field=models.CharField(blank=True, db_comment='股票代码', db_index=True, max_length=24, null=True, verbose_name='股票代码'),
        ),
        migrations.AlterField(
            model_name='stockbasic',
            name='ts_code',
            field=models.CharField(db_comment='TuShare股票代码', max_length=24, unique=True, verbose_name='TS股票代码'),
        ),
        migrations.AlterField(
            model_name='stockbasic',
            name='tushare_meta',
            field=models.JSONField(blank=True, db_comment='TuShare分类、接口和目标表元数据', default=dict, verbose_name='TuShare元数据'),
        ),
        migrations.AlterField(
            model_name='stockbasichistory',
            name='field_name',
            field=models.CharField(db_comment='发生变化的字段名', db_index=True, max_length=80, verbose_name='变更字段'),
        ),
        migrations.AlterField(
            model_name='stockbasichistory',
            name='new_value',
            field=models.TextField(blank=True, db_comment='变更后字段值', null=True, verbose_name='新值'),
        ),
        migrations.AlterField(
            model_name='stockbasichistory',
            name='old_value',
            field=models.TextField(blank=True, db_comment='变更前字段值', null=True, verbose_name='旧值'),
        ),
        migrations.AlterField(
            model_name='stockbasichistory',
            name='raw_record',
            field=models.JSONField(blank=True, db_comment='触发变更的TuShare原始记录', default=dict, verbose_name='原始记录'),
        ),
        migrations.AlterField(
            model_name='stockbasichistory',
            name='source_date',
            field=models.CharField(blank=True, db_comment='同步发现变更日期 YYYYMMDD', db_index=True, default='', max_length=8, verbose_name='来源日期'),
        ),
        migrations.AlterField(
            model_name='stockbasichistory',
            name='ts_code',
            field=models.CharField(db_comment='TuShare股票代码', db_index=True, max_length=24, verbose_name='TS股票代码'),
        ),
        migrations.AddIndex(
            model_name='stockbasic',
            index=models.Index(fields=['list_status', 'exchange'], name='ix_stkb_status_exchange'),
        ),
        migrations.AddIndex(
            model_name='stockbasic',
            index=models.Index(fields=['list_status', 'market'], name='ix_stkb_status_market'),
        ),
        migrations.AddIndex(
            model_name='stockbasic',
            index=models.Index(fields=['industry', 'area'], name='ix_stkb_industry_area'),
        ),
        migrations.AddIndex(
            model_name='stockbasic',
            index=models.Index(fields=['list_date'], name='ix_stkb_list_date'),
        ),
        migrations.AddIndex(
            model_name='stockbasic',
            index=models.Index(fields=['updated_at'], name='ix_stkb_updated_at'),
        ),
        migrations.AddIndex(
            model_name='stockbasichistory',
            index=models.Index(fields=['ts_code', 'field_name', 'created_at'], name='ix_stkbh_code_field'),
        ),
        migrations.AddIndex(
            model_name='stockbasichistory',
            index=models.Index(fields=['source_date', 'ts_code'], name='ix_stkbh_source_code'),
        ),
    ]
