# Generated by Django 6.0.3 on 2026-05-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_balancesheet_acc_exp_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.AlterField(
            model_name='financialindicator',
            name='assets_yoy',
            field=models.FloatField(blank=True, db_comment='资产总计相对年初增长率(%)', null=True, verbose_name='资产总计相对年初增长率(%)'),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='basic_eps_yoy',
            field=models.FloatField(blank=True, db_comment='基本每股收益同比增长率(%)', null=True, verbose_name='基本每股收益同比增长率(%)'),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='bps_yoy',
            field=models.FloatField(blank=True, db_comment='每股净资产相对年初增长率(%)', null=True, verbose_name='每股净资产相对年初增长率(%)'),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='cfps_yoy',
            field=models.FloatField(blank=True, db_comment='每股经营活动产生的现金流量净额同比增长率(%)', null=True, verbose_name='每股经营活动产生的现金流量净额同比增长率(%)'),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='dt_eps_yoy',
            field=models.FloatField(blank=True, db_comment='稀释每股收益同比增长率(%)', null=True, verbose_name='稀释每股收益同比增长率(%)'),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='dt_netprofit_yoy',
            field=models.FloatField(blank=True, db_comment='归属母公司股东的净利润-扣除非经常损益同比增长率(%)', null=True, verbose_name='归属母公司股东的净利润-扣除非经常损益同比增长率(%)'),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='ebt_yoy',
            field=models.FloatField(blank=True, db_comment='利润总额同比增长率(%)', null=True, verbose_name='利润总额同比增长率(%)'),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='eqt_yoy',
            field=models.FloatField(blank=True, db_comment='归属母公司的股东权益相对年初增长率(%)', null=True, verbose_name='归属母公司的股东权益相对年初增长率(%)'),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='netprofit_yoy',
            field=models.FloatField(blank=True, db_comment='归属母公司股东的净利润同比增长率(%)', null=True, verbose_name='归属母公司股东的净利润同比增长率(%)'),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='ocf_yoy',
            field=models.FloatField(blank=True, db_comment='经营活动产生的现金流量净额同比增长率(%)', null=True, verbose_name='经营活动产生的现金流量净额同比增长率(%)'),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='op_yoy',
            field=models.FloatField(blank=True, db_comment='营业利润同比增长率(%)', null=True, verbose_name='营业利润同比增长率(%)'),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='or_yoy',
            field=models.FloatField(blank=True, db_comment='营业收入同比增长率(%)', null=True, verbose_name='营业收入同比增长率(%)'),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='q_gr_qoq',
            field=models.FloatField(blank=True, db_comment='营业总收入环比增长率(%)(单季度)', null=True, verbose_name='营业总收入环比增长率(%)(单季度)'),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='q_gr_yoy',
            field=models.FloatField(blank=True, db_comment='营业总收入同比增长率(%)(单季度)', null=True, verbose_name='营业总收入同比增长率(%)(单季度)'),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='q_netprofit_qoq',
            field=models.FloatField(blank=True, db_comment='归属母公司股东的净利润环比增长率(%)(单季度)', null=True, verbose_name='归属母公司股东的净利润环比增长率(%)(单季度)'),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='q_netprofit_yoy',
            field=models.FloatField(blank=True, db_comment='归属母公司股东的净利润同比增长率(%)(单季度)', null=True, verbose_name='归属母公司股东的净利润同比增长率(%)(单季度)'),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='q_op_qoq',
            field=models.FloatField(blank=True, db_comment='营业利润环比增长率(%)(单季度)', null=True, verbose_name='营业利润环比增长率(%)(单季度)'),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='q_op_yoy',
            field=models.FloatField(blank=True, db_comment='营业利润同比增长率(%)(单季度)', null=True, verbose_name='营业利润同比增长率(%)(单季度)'),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='q_profit_qoq',
            field=models.FloatField(blank=True, db_comment='净利润环比增长率(%)(单季度)', null=True, verbose_name='净利润环比增长率(%)(单季度)'),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='q_profit_yoy',
            field=models.FloatField(blank=True, db_comment='净利润同比增长率(%)(单季度)', null=True, verbose_name='净利润同比增长率(%)(单季度)'),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='q_sales_qoq',
            field=models.FloatField(blank=True, db_comment='营业收入环比增长率(%)(单季度)', null=True, verbose_name='营业收入环比增长率(%)(单季度)'),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='q_sales_yoy',
            field=models.FloatField(blank=True, db_comment='营业收入同比增长率(%)(单季度)', null=True, verbose_name='营业收入同比增长率(%)(单季度)'),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='roe_yoy',
            field=models.FloatField(blank=True, db_comment='净资产收益率(摊薄)同比增长率(%)', null=True, verbose_name='净资产收益率(摊薄)同比增长率(%)'),
        ),
        migrations.AlterField(
            model_name='financialindicator',
            name='tr_yoy',
            field=models.FloatField(blank=True, db_comment='营业总收入同比增长率(%)', null=True, verbose_name='营业总收入同比增长率(%)'),
        ),            ],
        ),
    ]
