# Generated by Django 6.0.3 on 2026-05-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_blocktrade_dividend_marginsummary_performanceexpress_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.AlterField(
            model_name='performanceexpress',
            name='diluted_roe',
            field=models.FloatField(blank=True, db_comment='净资产收益率(摊薄)(%)', null=True, verbose_name='净资产收益率(摊薄)(%)'),
        ),
        migrations.AlterField(
            model_name='performanceforecast',
            name='p_change_max',
            field=models.FloatField(blank=True, db_comment='预告净利润变动幅度上限（%）', null=True, verbose_name='预告净利润变动幅度上限（%）'),
        ),
        migrations.AlterField(
            model_name='performanceforecast',
            name='p_change_min',
            field=models.FloatField(blank=True, db_comment='预告净利润变动幅度下限（%）', null=True, verbose_name='预告净利润变动幅度下限（%）'),
        ),
        migrations.AlterField(
            model_name='stockfactorpro',
            name='dv_ratio',
            field=models.FloatField(blank=True, db_comment='股息率 （%）', null=True, verbose_name='股息率 （%）'),
        ),
        migrations.AlterField(
            model_name='stockfactorpro',
            name='dv_ttm',
            field=models.FloatField(blank=True, db_comment='股息率（TTM）（%）', null=True, verbose_name='股息率（TTM）（%）'),
        ),
        migrations.AlterField(
            model_name='stockfactorpro',
            name='turnover_rate',
            field=models.FloatField(blank=True, db_comment='换手率（%）', null=True, verbose_name='换手率（%）'),
        ),            ],
        ),
    ]
