# Generated by Django 6.0.3 on 2026-05-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_performanceexpress_diluted_roe_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='margindetail',
            name='uniq_margin_detail_code_date_ex',
        ),
        migrations.AddConstraint(
            model_name='margindetail',
            constraint=models.UniqueConstraint(fields=('ts_code', 'trade_date'), name='uniq_margin_detail_code_date'),
        ),
    ]
