# Generated by Django 6.0.3 on 2026-05-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_margindetail_uniq_margin_detail_code_date_ex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topinst',
            name='buy_rate',
            field=models.FloatField(blank=True, db_comment='买入占比', null=True, verbose_name='买入占比'),
        ),
        migrations.AddField(
            model_name='topinst',
            name='exalter',
            field=models.CharField(blank=True, db_comment='营业部名称', max_length=240, null=True, verbose_name='营业部名称'),
        ),
        migrations.AddField(
            model_name='topinst',
            name='net_buy',
            field=models.FloatField(blank=True, db_comment='净买入额', null=True, verbose_name='净买入额'),
        ),
        migrations.AddField(
            model_name='topinst',
            name='reason',
            field=models.TextField(blank=True, db_comment='上榜理由', null=True, verbose_name='上榜理由'),
        ),
        migrations.AddField(
            model_name='topinst',
            name='sell_rate',
            field=models.FloatField(blank=True, db_comment='卖出占比', null=True, verbose_name='卖出占比'),
        ),
        migrations.AddField(
            model_name='topinst',
            name='side',
            field=models.CharField(blank=True, db_comment='买卖类型', max_length=16, null=True, verbose_name='买卖类型'),
        ),
        migrations.AddField(
            model_name='toplist',
            name='amount_rate',
            field=models.FloatField(blank=True, db_comment='成交额占总成交比例', null=True, verbose_name='成交额占总成交比例'),
        ),
        migrations.AddField(
            model_name='toplist',
            name='float_values',
            field=models.FloatField(blank=True, db_comment='流通市值', null=True, verbose_name='流通市值'),
        ),
        migrations.AddField(
            model_name='toplist',
            name='l_amount',
            field=models.FloatField(blank=True, db_comment='龙虎榜成交额', null=True, verbose_name='龙虎榜成交额'),
        ),
        migrations.AddField(
            model_name='toplist',
            name='l_buy',
            field=models.FloatField(blank=True, db_comment='龙虎榜买入额', null=True, verbose_name='龙虎榜买入额'),
        ),
        migrations.AddField(
            model_name='toplist',
            name='l_sell',
            field=models.FloatField(blank=True, db_comment='龙虎榜卖出额', null=True, verbose_name='龙虎榜卖出额'),
        ),
        migrations.AddField(
            model_name='toplist',
            name='net_rate',
            field=models.FloatField(blank=True, db_comment='净买入额占总成交比例', null=True, verbose_name='净买入额占总成交比例'),
        ),
        migrations.AddField(
            model_name='toplist',
            name='pct_change',
            field=models.FloatField(blank=True, db_comment='涨跌幅', null=True, verbose_name='涨跌幅'),
        ),
        migrations.AddField(
            model_name='toplist',
            name='reason',
            field=models.TextField(blank=True, db_comment='上榜理由', null=True, verbose_name='上榜理由'),
        ),
        migrations.AddField(
            model_name='toplist',
            name='turnover_rate',
            field=models.FloatField(blank=True, db_comment='换手率', null=True, verbose_name='换手率'),
        ),
    ]
