# Generated by Django 6.0.3 on 2026-05-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_topinst_buy_rate_topinst_exalter_topinst_net_buy_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='topinst',
            name='uniq_top_inst',
        ),
        migrations.RemoveConstraint(
            model_name='toplist',
            name='uniq_top_list',
        ),
        migrations.RemoveIndex(
            model_name='topinst',
            name='ix_top_inst_1',
        ),
        migrations.RemoveIndex(
            model_name='toplist',
            name='ix_top_list_1',
        ),
        migrations.AddField(
            model_name='topinst',
            name='buy',
            field=models.FloatField(blank=True, db_comment='买入额', null=True, verbose_name='买入额'),
        ),
        migrations.AddField(
            model_name='topinst',
            name='sell',
            field=models.FloatField(blank=True, db_comment='卖出额', null=True, verbose_name='卖出额'),
        ),
        migrations.AddIndex(
            model_name='topinst',
            index=models.Index(fields=['trade_date', 'ts_code'], name='ix_top_inst_1'),
        ),
        migrations.AddIndex(
            model_name='toplist',
            index=models.Index(fields=['trade_date', 'ts_code'], name='ix_top_list_1'),
        ),
        migrations.AddConstraint(
            model_name='topinst',
            constraint=models.UniqueConstraint(fields=('ts_code', 'trade_date', 'exalter', 'side', 'reason'), name='uniq_top_inst'),
        ),
        migrations.AddConstraint(
            model_name='toplist',
            constraint=models.UniqueConstraint(fields=('ts_code', 'trade_date', 'reason'), name='uniq_top_list'),
        ),
    ]
