"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(path):
    if not path.exists():
        return

    for raw_line in path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


load_env_file(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-by=jbdho9@c*dkdam%4cc+d2mqeclc(y-%&y5=pmv=bk3ur98w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes', 'on')

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.staticfiles',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Business data uses PostgreSQL through Django ORM models.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'finance_db'),
        'USER': os.getenv('POSTGRES_USER', 'finance_app'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'finance_app'),
        'HOST': os.getenv('POSTGRES_HOST', '127.0.0.1'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
        'OPTIONS': {
            'connect_timeout': int(os.getenv('POSTGRES_CONNECT_TIMEOUT', '5')),
        },
    }
}

POSTGRES_TUSHARE_TABLES = {
    'stock_basic': 'tushare_stock_basic',
    'trade_cal': 'tushare_trade_cal',
    'stk_premarket': 'tushare_stk_premarket',
    'stock_st': 'tushare_stock_st',
    'st': 'tushare_st_risk_notice',
    'stock_hsgt': 'tushare_stock_hsgt',
    'namechange': 'tushare_stock_namechange',
    'stock_company': 'tushare_stock_company',
    'daily': 'tushare_stock_daily',
    'daily_basic': 'tushare_stock_daily_basic',
    'sync_jobs': 'system_sync_jobs',
}

REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1')

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
    }
}

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/2')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = os.getenv('CELERY_TIMEZONE', 'UTC')

TUSHARE_TOKEN = os.getenv('TUSHARE_TOKEN', '')
TUSHARE_SYNC_START_DATE = os.getenv('TUSHARE_SYNC_START_DATE', '20240101')
TUSHARE_FULL_SYNC_START_DATE = os.getenv('TUSHARE_FULL_SYNC_START_DATE', '19901219')
TUSHARE_SYNC_DAYS_BACK = int(os.getenv('TUSHARE_SYNC_DAYS_BACK', '7'))
TUSHARE_SYNC_INTERVALS = {
    'stock_basic': int(os.getenv('TUSHARE_STOCK_BASIC_SYNC_INTERVAL_SECONDS', str(60 * 60 * 24 * 7))),
    'trade_cal': int(os.getenv('TUSHARE_TRADE_CAL_SYNC_INTERVAL_SECONDS', str(60 * 60 * 24))),
    'stk_premarket': int(os.getenv('TUSHARE_STK_PREMARKET_SYNC_INTERVAL_SECONDS', str(60 * 60 * 24))),
    'stock_st': int(os.getenv('TUSHARE_STOCK_ST_SYNC_INTERVAL_SECONDS', str(60 * 60 * 24))),
    'st': int(os.getenv('TUSHARE_ST_RISK_SYNC_INTERVAL_SECONDS', str(60 * 60 * 24 * 7))),
    'stock_hsgt': int(os.getenv('TUSHARE_STOCK_HSGT_SYNC_INTERVAL_SECONDS', str(60 * 60 * 24))),
    'namechange': int(os.getenv('TUSHARE_NAMECHANGE_SYNC_INTERVAL_SECONDS', str(60 * 60 * 24 * 7))),
    'stock_company': int(os.getenv('TUSHARE_STOCK_COMPANY_SYNC_INTERVAL_SECONDS', str(60 * 60 * 24 * 7))),
    'daily': int(os.getenv('TUSHARE_DAILY_SYNC_INTERVAL_SECONDS', str(60 * 60 * 24))),
    'daily_basic': int(os.getenv('TUSHARE_DAILY_BASIC_SYNC_INTERVAL_SECONDS', str(60 * 60 * 24))),
}

CELERY_BEAT_SCHEDULE = {
    'sync-tushare-stock-basic': {
        'task': 'api.tasks.sync_tushare_stock_basic',
        'schedule': TUSHARE_SYNC_INTERVALS['stock_basic'],
    },
    'sync-tushare-trade-cal': {
        'task': 'api.tasks.sync_tushare_trade_cal',
        'schedule': TUSHARE_SYNC_INTERVALS['trade_cal'],
    },
    'sync-tushare-stk-premarket': {
        'task': 'api.tasks.sync_tushare_stk_premarket',
        'schedule': TUSHARE_SYNC_INTERVALS['stk_premarket'],
    },
    'sync-tushare-stock-st': {
        'task': 'api.tasks.sync_tushare_stock_st',
        'schedule': TUSHARE_SYNC_INTERVALS['stock_st'],
    },
    'sync-tushare-st-risk': {
        'task': 'api.tasks.sync_tushare_st_risk',
        'schedule': TUSHARE_SYNC_INTERVALS['st'],
    },
    'sync-tushare-stock-hsgt': {
        'task': 'api.tasks.sync_tushare_stock_hsgt',
        'schedule': TUSHARE_SYNC_INTERVALS['stock_hsgt'],
    },
    'sync-tushare-namechange': {
        'task': 'api.tasks.sync_tushare_namechange',
        'schedule': TUSHARE_SYNC_INTERVALS['namechange'],
    },
    'sync-tushare-stock-company': {
        'task': 'api.tasks.sync_tushare_stock_company',
        'schedule': TUSHARE_SYNC_INTERVALS['stock_company'],
    },
    'sync-tushare-daily-quote': {
        'task': 'api.tasks.sync_tushare_daily_quote',
        'schedule': TUSHARE_SYNC_INTERVALS['daily'],
    },
    'sync-tushare-daily-basic': {
        'task': 'api.tasks.sync_tushare_daily_basic',
        'schedule': TUSHARE_SYNC_INTERVALS['daily_basic'],
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
