from django.conf import settings

from api.models import (
    Repurchase,
    Dividend,
    TopInst,
    TopList,
    BlockTrade,
    PerformanceExpress,
    PerformanceForecast,
    PledgeDetail,
    MarginSummary,
    StockFactorPro,
    AdjFactor,
    BalanceSheet,
    CashFlowStatement,
    DailyBasic,
    DailyQuote,
    FinancialIndicator,
    HkHold,
    IncomeStatement,
    IndexBasic,
    IndexClassify,
    IndexDaily,
    IndexMemberAll,
    MarginDetail,
    PledgeStat,
    ShareFloat,
    StockBasic,
    StockBasicHistory,
    StockCapitalPremarket,
    StockCompany,
    StockHsgt,
    StockLimit,
    StockMoneyflow,
    StockNameChange,
    StockSTList,
    StockSTRiskNotice,
    SuspendDetail,
    SyncJob,
    TradeCal,
)


TABLES = settings.POSTGRES_TUSHARE_TABLES

TUSHARE_CATALOG = {
    'stock_basic': {
        'category': '股票数据',
        'section': '基础数据',
        'interface': 'stock_basic',
        'table': TABLES['stock_basic'],
    },
    'trade_cal': {
        'category': '股票数据',
        'section': '基础数据',
        'interface': 'trade_cal',
        'table': TABLES['trade_cal'],
    },
    'stk_premarket': {
        'category': '股票数据',
        'section': '基础数据',
        'interface': 'stk_premarket',
        'table': TABLES['stk_premarket'],
    },
    'stock_st': {
        'category': '股票数据',
        'section': '基础数据',
        'interface': 'stock_st',
        'table': TABLES['stock_st'],
    },
    'st': {
        'category': '股票数据',
        'section': '基础数据',
        'interface': 'st',
        'table': TABLES['st'],
    },
    'stock_hsgt': {
        'category': '股票数据',
        'section': '基础数据',
        'interface': 'stock_hsgt',
        'table': TABLES['stock_hsgt'],
    },
    'namechange': {
        'category': '股票数据',
        'section': '基础数据',
        'interface': 'namechange',
        'table': TABLES['namechange'],
    },
    'stock_company': {
        'category': '股票数据',
        'section': '基础数据',
        'interface': 'stock_company',
        'table': TABLES['stock_company'],
    },
    'daily': {
        'category': '股票数据',
        'section': '行情数据',
        'interface': 'daily',
        'table': TABLES['daily'],
    },
    'daily_basic': {
        'category': '股票数据',
        'section': '行情数据',
        'interface': 'daily_basic',
        'table': TABLES['daily_basic'],
    },
    'adj_factor': {
        'category': '股票数据',
        'section': '行情数据',
        'interface': 'adj_factor',
        'table': TABLES['adj_factor'],
    },
    'fina_indicator': {
        'category': '股票数据',
        'section': '财务数据',
        'interface': 'fina_indicator',
        'table': TABLES['fina_indicator'],
    },
    'income': {
        'category': '股票数据',
        'section': '财务数据',
        'interface': 'income',
        'table': TABLES['income'],
    },
    'balancesheet': {
        'category': '股票数据',
        'section': '财务数据',
        'interface': 'balancesheet',
        'table': TABLES['balancesheet'],
    },
    'cashflow': {
        'category': '股票数据',
        'section': '财务数据',
        'interface': 'cashflow',
        'table': TABLES['cashflow'],
    },
    'index_basic': {
        'category': '指数数据',
        'section': '基础数据',
        'interface': 'index_basic',
        'table': TABLES['index_basic'],
    },
    'index_daily': {
        'category': '指数数据',
        'section': '行情数据',
        'interface': 'index_daily',
        'table': TABLES['index_daily'],
    },
    'index_classify': {
        'category': '指数数据',
        'section': '申万行业',
        'interface': 'index_classify',
        'table': TABLES['index_classify'],
    },
    'index_member_all': {
        'category': '指数数据',
        'section': '申万行业',
        'interface': 'index_member_all',
        'table': TABLES['index_member_all'],
    },
    'moneyflow': {
        'category': '股票数据',
        'section': '资金流向',
        'interface': 'moneyflow',
        'table': TABLES['moneyflow'],
    },
    'margin_detail': {
        'category': '股票数据',
        'section': '融资融券',
        'interface': 'margin_detail',
        'table': TABLES['margin_detail'],
    },
    'hk_hold': {
        'category': '股票数据',
        'section': '沪深股通',
        'interface': 'hk_hold',
        'table': TABLES['hk_hold'],
    },
    'suspend_d': {
        'category': '股票数据',
        'section': '停复牌',
        'interface': 'suspend_d',
        'table': TABLES['suspend_d'],
    },
    'stk_limit': {
        'category': '股票数据',
        'section': '行情数据',
        'interface': 'stk_limit',
        'table': TABLES['stk_limit'],
    },
    'share_float': {
        'category': '股票数据',
        'section': '限售解禁',
        'interface': 'share_float',
        'table': TABLES['share_float'],
    },
    'pledge_stat': {
        'category': '股票数据',
        'section': '股权质押',
        'interface': 'pledge_stat',
        'table': TABLES['pledge_stat'],
    },
    'stk_factor_pro': {
        'category': '????',
        'section': '????',
        'interface': 'stk_factor_pro',
        'table': TABLES['stk_factor_pro'],
    },
    'margin': {
        'category': '????',
        'section': '????',
        'interface': 'margin',
        'table': TABLES['margin'],
    },
    'pledge_detail': {
        'category': '????',
        'section': '????',
        'interface': 'pledge_detail',
        'table': TABLES['pledge_detail'],
    },
    'forecast': {
        'category': '????',
        'section': '????',
        'interface': 'forecast',
        'table': TABLES['forecast'],
    },
    'express': {
        'category': '????',
        'section': '????',
        'interface': 'express',
        'table': TABLES['express'],
    },
    'block_trade': {
        'category': '????',
        'section': '????',
        'interface': 'block_trade',
        'table': TABLES['block_trade'],
    },
    'top_list': {
        'category': '????',
        'section': '???',
        'interface': 'top_list',
        'table': TABLES['top_list'],
    },
    'top_inst': {
        'category': '????',
        'section': '???',
        'interface': 'top_inst',
        'table': TABLES['top_inst'],
    },
    'dividend': {
        'category': '????',
        'section': '????',
        'interface': 'dividend',
        'table': TABLES['dividend'],
    },
    'repurchase': {
        'category': '????',
        'section': '????',
        'interface': 'repurchase',
        'table': TABLES['repurchase'],
    },
}

MODEL_CONFIG = {
    'stock_basic': {
        'model': StockBasic,
        'fields': [
            'ts_code', 'symbol', 'name', 'area', 'industry', 'fullname', 'enname', 'cnspell',
            'market', 'exchange', 'curr_type', 'list_status', 'list_date', 'delist_date',
            'is_hs', 'act_name', 'act_ent_type',
        ],
    },
    'stock_basic_history': {
        'model': StockBasicHistory,
        'fields': ['ts_code', 'field_name', 'old_value', 'new_value', 'source_date', 'raw_record'],
    },
    'trade_cal': {
        'model': TradeCal,
        'fields': ['exchange', 'cal_date', 'is_open', 'pretrade_date'],
    },
    'stk_premarket': {
        'model': StockCapitalPremarket,
        'fields': ['trade_date', 'ts_code', 'total_share', 'float_share', 'pre_close', 'up_limit', 'down_limit'],
    },
    'stock_st': {
        'model': StockSTList,
        'fields': ['ts_code', 'name', 'trade_date', 'type', 'type_name'],
    },
    'st': {
        'model': StockSTRiskNotice,
        'fields': ['ts_code', 'name', 'pub_date', 'imp_date', 'st_tpye', 'st_reason', 'st_explain'],
    },
    'stock_hsgt': {
        'model': StockHsgt,
        'fields': ['ts_code', 'trade_date', 'type', 'name', 'type_name'],
    },
    'namechange': {
        'model': StockNameChange,
        'fields': ['ts_code', 'name', 'start_date', 'end_date', 'ann_date', 'change_reason'],
    },
    'stock_company': {
        'model': StockCompany,
        'fields': [
            'ts_code', 'com_name', 'com_id', 'exchange', 'chairman', 'manager', 'secretary',
            'reg_capital', 'setup_date', 'province', 'city', 'introduction', 'website', 'email',
            'office', 'employees', 'main_business', 'business_scope',
        ],
    },
    'daily': {
        'model': DailyQuote,
        'fields': ['ts_code', 'trade_date', 'open', 'high', 'low', 'close', 'pre_close', 'change', 'pct_chg', 'vol', 'amount'],
    },
    'daily_basic': {
        'model': DailyBasic,
        'fields': ['ts_code', 'trade_date', 'close', 'turnover_rate', 'volume_ratio', 'pe_ttm', 'pb', 'ps_ttm', 'dv_ttm', 'total_mv', 'circ_mv'],
    },
    'adj_factor': {
        'model': AdjFactor,
        'fields': ['ts_code', 'trade_date', 'adj_factor'],
    },
    'fina_indicator': {
        'model': FinancialIndicator,
        'fields': [
            'ts_code', 'ann_date', 'end_date', 'eps', 'dt_eps', 'total_revenue_ps', 'revenue_ps',
            'capital_rese_ps', 'surplus_rese_ps', 'undist_profit_ps', 'extra_item', 'profit_dedt',
            'gross_margin', 'current_ratio', 'quick_ratio', 'cash_ratio', 'invturn_days',
            'arturn_days', 'inv_turn', 'ar_turn', 'ca_turn', 'fa_turn', 'assets_turn',
            'op_income', 'valuechange_income', 'interst_income', 'daa', 'ebit', 'ebitda',
            'fcff', 'fcfe', 'current_exint', 'noncurrent_exint', 'interestdebt', 'netdebt',
            'tangible_asset', 'working_capital', 'networking_capital', 'invest_capital',
            'retained_earnings', 'diluted2_eps', 'bps', 'ocfps', 'retainedps', 'cfps',
            'ebit_ps', 'fcff_ps', 'fcfe_ps', 'netprofit_margin', 'grossprofit_margin',
            'cogs_of_sales', 'expense_of_sales', 'profit_to_gr', 'saleexp_to_gr',
            'adminexp_of_gr', 'finaexp_of_gr', 'impai_ttm', 'gc_of_gr', 'op_of_gr',
            'ebit_of_gr', 'roe', 'roe_waa', 'roe_dt', 'roa', 'npta', 'roic',
            'roe_yearly', 'roa2_yearly', 'roe_avg', 'opincome_of_ebt', 'investincome_of_ebt',
            'n_op_profit_of_ebt', 'tax_to_ebt', 'dtprofit_to_profit', 'salescash_to_or',
            'ocf_to_or', 'ocf_to_opincome', 'capitalized_to_da', 'debt_to_assets',
            'assets_to_eqt', 'dp_assets_to_eqt', 'ca_to_assets', 'nca_to_assets',
            'tbassets_to_totalassets', 'int_to_talcap', 'eqt_to_talcapital',
            'currentdebt_to_debt', 'longdeb_to_debt', 'ocf_to_shortdebt', 'debt_to_eqt',
            'eqt_to_debt', 'eqt_to_interestdebt', 'tangibleasset_to_debt',
            'tangasset_to_intdebt', 'tangibleasset_to_netdebt', 'ocf_to_debt', 'turn_days',
            'roa_yearly', 'roa_dp', 'fixed_assets', 'profit_prefin_exp', 'non_op_profit',
            'op_to_ebt', 'nop_to_ebt', 'ocf_to_profit', 'cash_to_liqdebt',
            'cash_to_liqdebt_withinterest', 'op_to_liqdebt', 'op_to_debt', 'roic_yearly',
            'total_fa_trun', 'profit_to_op', 'q_opincome', 'q_investincome', 'q_dtprofit',
            'q_eps', 'q_netprofit_margin', 'q_gsprofit_margin', 'q_exp_to_sales',
            'q_profit_to_gr', 'q_saleexp_to_gr', 'q_adminexp_to_gr', 'q_finaexp_to_gr',
            'q_impair_to_gr_ttm', 'q_gc_to_gr', 'q_op_to_gr', 'q_roe', 'q_dt_roe',
            'q_npta', 'q_opincome_to_ebt', 'q_investincome_to_ebt', 'q_dtprofit_to_profit',
            'q_salescash_to_or', 'q_ocf_to_sales', 'q_ocf_to_or', 'basic_eps_yoy',
            'dt_eps_yoy', 'cfps_yoy', 'op_yoy', 'ebt_yoy', 'netprofit_yoy',
            'dt_netprofit_yoy', 'ocf_yoy', 'roe_yoy', 'bps_yoy', 'assets_yoy',
            'eqt_yoy', 'tr_yoy', 'or_yoy', 'q_gr_yoy', 'q_gr_qoq', 'q_sales_yoy',
            'q_sales_qoq', 'q_op_yoy', 'q_op_qoq', 'q_profit_yoy', 'q_profit_qoq',
            'q_netprofit_yoy', 'q_netprofit_qoq', 'equity_yoy', 'rd_exp', 'update_flag',
        ],
    },
    'income': {
        'model': IncomeStatement,
        'fields': [
            'ts_code', 'ann_date', 'f_ann_date', 'end_date', 'report_type', 'comp_type',
            'end_type', 'basic_eps', 'diluted_eps', 'total_revenue', 'revenue', 'int_income',
            'prem_earned', 'comm_income', 'n_commis_income', 'n_oth_income', 'n_oth_b_income',
            'prem_income', 'out_prem', 'une_prem_reser', 'reins_income', 'n_sec_tb_income',
            'n_sec_uw_income', 'n_asset_mg_income', 'oth_b_income', 'fv_value_chg_gain',
            'invest_income', 'ass_invest_income', 'forex_gain', 'total_cogs', 'oper_cost',
            'int_exp', 'comm_exp', 'biz_tax_surchg', 'sell_exp', 'admin_exp', 'fin_exp',
            'assets_impair_loss', 'prem_refund', 'compens_payout', 'reser_insur_liab',
            'div_payt', 'reins_exp', 'oper_exp', 'compens_payout_refu', 'insur_reser_refu',
            'reins_cost_refund', 'other_bus_cost', 'operate_profit', 'non_oper_income',
            'non_oper_exp', 'nca_disploss', 'total_profit', 'income_tax', 'n_income',
            'n_income_attr_p', 'minority_gain', 'oth_compr_income', 't_compr_income',
            'compr_inc_attr_p', 'compr_inc_attr_m_s', 'ebit', 'ebitda', 'insurance_exp',
            'undist_profit', 'distable_profit', 'rd_exp', 'fin_exp_int_exp', 'fin_exp_int_inc',
            'transfer_surplus_rese', 'transfer_housing_imprest', 'transfer_oth', 'adj_lossgain',
            'withdra_legal_surplus', 'withdra_legal_pubfund', 'withdra_biz_devfund',
            'withdra_rese_fund', 'withdra_oth_ersu', 'workers_welfare', 'distr_profit_shrhder',
            'prfshare_payable_dvd', 'comshare_payable_dvd', 'capit_comstock_div',
            'net_after_nr_lp_correct', 'credit_impa_loss', 'net_expo_hedging_benefits',
            'oth_impair_loss_assets', 'total_opcost', 'amodcost_fin_assets', 'oth_income',
            'asset_disp_income', 'continued_net_profit', 'end_net_profit', 'update_flag',
        ],
    },
    'balancesheet': {
        'model': BalanceSheet,
        'fields': [
            'ts_code', 'ann_date', 'f_ann_date', 'end_date', 'report_type', 'comp_type',
            'end_type', 'total_share', 'cap_rese', 'undistr_porfit', 'surplus_rese',
            'special_rese', 'money_cap', 'trad_asset', 'notes_receiv', 'accounts_receiv',
            'oth_receiv', 'prepayment', 'div_receiv', 'int_receiv', 'inventories',
            'amor_exp', 'nca_within_1y', 'sett_rsrv', 'loanto_oth_bank_fi', 'premium_receiv',
            'reinsur_receiv', 'reinsur_res_receiv', 'pur_resale_fa', 'oth_cur_assets',
            'total_cur_assets', 'fa_avail_for_sale', 'htm_invest', 'lt_eqt_invest',
            'invest_real_estate', 'time_deposits', 'oth_assets', 'lt_rec', 'fix_assets',
            'cip', 'const_materials', 'fixed_assets_disp', 'produc_bio_assets',
            'oil_and_gas_assets', 'intan_assets', 'r_and_d', 'goodwill', 'lt_amor_exp',
            'defer_tax_assets', 'decr_in_disbur', 'oth_nca', 'total_nca', 'cash_reser_cb',
            'depos_in_oth_bfi', 'prec_metals', 'deriv_assets', 'rr_reins_une_prem',
            'rr_reins_outstd_cla', 'rr_reins_lins_liab', 'rr_reins_lthins_liab',
            'refund_depos', 'ph_pledge_loans', 'refund_cap_depos', 'indep_acct_assets',
            'client_depos', 'client_prov', 'transac_seat_fee', 'invest_as_receiv',
            'total_assets', 'lt_borr', 'st_borr', 'cb_borr', 'depos_ib_deposits',
            'loan_oth_bank', 'trading_fl', 'notes_payable', 'acct_payable', 'adv_receipts',
            'sold_for_repur_fa', 'comm_payable', 'payroll_payable', 'taxes_payable',
            'int_payable', 'div_payable', 'oth_payable', 'acc_exp', 'deferred_inc',
            'st_bonds_payable', 'payable_to_reinsurer', 'rsrv_insur_cont', 'acting_trading_sec',
            'acting_uw_sec', 'non_cur_liab_due_1y', 'oth_cur_liab', 'total_cur_liab',
            'bond_payable', 'lt_payable', 'specific_payables', 'estimated_liab',
            'defer_tax_liab', 'defer_inc_non_cur_liab', 'oth_ncl', 'total_ncl',
            'depos_oth_bfi', 'deriv_liab', 'depos', 'agency_bus_liab', 'oth_liab',
            'prem_receiv_adva', 'depos_received', 'ph_invest', 'reser_une_prem',
            'reser_outstd_claims', 'reser_lins_liab', 'reser_lthins_liab', 'indept_acc_liab',
            'pledge_borr', 'indem_payable', 'policy_div_payable', 'total_liab',
            'treasury_share', 'ordin_risk_reser', 'forex_differ', 'invest_loss_unconf',
            'minority_int', 'total_hldr_eqy_exc_min_int', 'total_hldr_eqy_inc_min_int',
            'total_liab_hldr_eqy', 'lt_payroll_payable', 'oth_comp_income', 'oth_eqt_tools',
            'oth_eqt_tools_p_shr', 'lending_funds', 'acc_receivable', 'st_fin_payable',
            'payables', 'hfs_assets', 'hfs_sales', 'cost_fin_assets', 'fair_value_fin_assets',
            'contract_assets', 'contract_liab', 'accounts_receiv_bill', 'accounts_pay',
            'oth_rcv_total', 'fix_assets_total', 'cip_total', 'oth_pay_total', 'long_pay_total',
            'debt_invest', 'oth_debt_invest', 'oth_eq_invest', 'oth_illiq_fin_assets',
            'oth_eq_ppbond', 'receiv_financing', 'update_flag',
        ],
    },
    'cashflow': {
        'model': CashFlowStatement,
        'fields': [
            'ts_code', 'ann_date', 'f_ann_date', 'end_date', 'comp_type', 'report_type',
            'end_type', 'net_profit', 'finan_exp', 'c_fr_sale_sg', 'recp_tax_rends',
            'n_depos_incr_fi', 'n_incr_loans_cb', 'n_inc_borr_oth_fi', 'prem_fr_orig_contr',
            'n_incr_insured_dep', 'n_reinsur_prem', 'n_incr_disp_tfa', 'ifc_cash_incr',
            'n_incr_disp_faas', 'n_incr_loans_oth_bank', 'n_cap_incr_repur',
            'c_fr_oth_operate_a', 'c_inf_fr_operate_a', 'c_paid_goods_s',
            'c_paid_to_for_empl', 'c_paid_for_taxes', 'n_incr_clt_loan_adv',
            'n_incr_dep_cbob', 'c_pay_claims_orig_inco', 'pay_handling_chrg',
            'pay_comm_insur_plcy', 'oth_cash_pay_oper_act', 'st_cash_out_act',
            'n_cashflow_act', 'oth_recp_ral_inv_act', 'c_disp_withdrwl_invest',
            'c_recp_return_invest', 'n_recp_disp_fiolta', 'n_recp_disp_sobu',
            'stot_inflows_inv_act', 'c_pay_acq_const_fiolta', 'c_paid_invest',
            'n_disp_subs_oth_biz', 'oth_pay_ral_inv_act', 'n_incr_pledge_loan',
            'stot_out_inv_act', 'n_cashflow_inv_act', 'c_recp_borrow', 'proc_issue_bonds',
            'oth_cash_recp_ral_fnc_act', 'stot_cash_in_fnc_act', 'free_cashflow',
            'c_prepay_amt_borr', 'c_pay_dist_dpcp_int_exp', 'incl_dvd_profit_paid_sc_ms',
            'oth_cashpay_ral_fnc_act', 'stot_cashout_fnc_act', 'n_cash_flows_fnc_act',
            'eff_fx_flu_cash', 'n_incr_cash_cash_equ', 'c_cash_equ_beg_period',
            'c_cash_equ_end_period', 'c_recp_cap_contrib', 'incl_cash_rec_saims',
            'uncon_invest_loss', 'prov_depr_assets', 'depr_fa_coga_dpba',
            'amort_intang_assets', 'lt_amort_deferred_exp', 'decr_deferred_exp',
            'incr_acc_exp', 'loss_disp_fiolta', 'loss_scr_fa', 'loss_fv_chg',
            'invest_loss', 'decr_def_inc_tax_assets', 'incr_def_inc_tax_liab',
            'decr_inventories', 'decr_oper_payable', 'incr_oper_payable', 'others',
            'im_net_cashflow_oper_act', 'conv_debt_into_cap', 'conv_copbonds_due_within_1y',
            'fa_fnc_leases', 'end_bal_cash', 'beg_bal_cash', 'end_bal_cash_equ',
            'beg_bal_cash_equ', 'im_n_incr_cash_equ', 'update_flag',
        ],
    },
    'index_basic': {
        'model': IndexBasic,
        'fields': [
            'ts_code', 'name', 'fullname', 'market', 'publisher', 'index_type', 'category',
            'base_date', 'base_point', 'list_date', 'weight_rule', 'desc', 'exp_date',
        ],
    },
    'index_daily': {
        'model': IndexDaily,
        'fields': ['ts_code', 'trade_date', 'close', 'open', 'high', 'low', 'pre_close', 'change', 'pct_chg', 'vol', 'amount'],
    },
    'index_classify': {
        'model': IndexClassify,
        'fields': ['index_code', 'industry_name', 'level', 'industry_code', 'is_pub', 'parent_code', 'src'],
    },
    'index_member_all': {
        'model': IndexMemberAll,
        'fields': ['l1_code', 'l1_name', 'l2_code', 'l2_name', 'l3_code', 'l3_name', 'ts_code', 'name', 'in_date', 'out_date', 'is_new'],
    },
    'moneyflow': {
        'model': StockMoneyflow,
        'fields': [
            'ts_code', 'trade_date', 'buy_sm_vol', 'buy_sm_amount', 'sell_sm_vol',
            'sell_sm_amount', 'buy_md_vol', 'buy_md_amount', 'sell_md_vol', 'sell_md_amount',
            'buy_lg_vol', 'buy_lg_amount', 'sell_lg_vol', 'sell_lg_amount',
            'buy_elg_vol', 'buy_elg_amount', 'sell_elg_vol', 'sell_elg_amount',
            'net_mf_vol', 'net_mf_amount',
        ],
    },
    'margin_detail': {
        'model': MarginDetail,
        'fields': ['trade_date', 'ts_code', 'name', 'rzye', 'rqye', 'rzmre', 'rqyl', 'rzche', 'rqchl', 'rqmcl', 'rzrqye', 'exchange_id'],
    },
    'hk_hold': {
        'model': HkHold,
        'fields': ['ts_code', 'trade_date', 'code', 'name', 'vol', 'ratio', 'exchange'],
    },
    'suspend_d': {
        'model': SuspendDetail,
        'fields': ['ts_code', 'suspend_date', 'resume_date', 'ann_date', 'suspend_reason', 'reason_type'],
    },
    'stk_limit': {
        'model': StockLimit,
        'fields': ['ts_code', 'trade_date', 'up_limit', 'down_limit', 'pre_close'],
    },
    'share_float': {
        'model': ShareFloat,
        'fields': ['ts_code', 'ann_date', 'float_date', 'float_share', 'float_ratio', 'holder_name', 'share_type'],
    },
    'pledge_stat': {
        'model': PledgeStat,
        'fields': ['ts_code', 'end_date', 'pledge_count', 'unrest_pledge', 'rest_pledge', 'total_share', 'pledge_ratio'],
    },
    'stk_factor_pro': {
        'model': StockFactorPro,
        'fields': ['ts_code', 'trade_date', 'open', 'open_hfq', 'open_qfq', 'high', 'high_hfq', 'high_qfq', 'low', 'low_hfq', 'low_qfq', 'close', 'close_hfq', 'close_qfq', 'pre_close', 'change', 'pct_chg', 'vol', 'amount', 'turnover_rate', 'turnover_rate_f', 'volume_ratio', 'pe', 'pe_ttm', 'pb', 'ps', 'ps_ttm', 'dv_ratio', 'dv_ttm', 'total_share', 'float_share', 'free_share', 'total_mv', 'circ_mv', 'adj_factor', 'asi_bfq', 'asi_hfq', 'asi_qfq', 'asit_bfq', 'asit_hfq', 'asit_qfq', 'atr_bfq', 'atr_hfq', 'atr_qfq', 'bbi_bfq', 'bbi_hfq', 'bbi_qfq', 'bias1_bfq', 'bias1_hfq', 'bias1_qfq', 'bias2_bfq', 'bias2_hfq', 'bias2_qfq', 'bias3_bfq', 'bias3_hfq', 'bias3_qfq', 'boll_lower_bfq', 'boll_lower_hfq', 'boll_lower_qfq', 'boll_mid_bfq', 'boll_mid_hfq', 'boll_mid_qfq', 'boll_upper_bfq', 'boll_upper_hfq', 'boll_upper_qfq', 'brar_ar_bfq', 'brar_ar_hfq', 'brar_ar_qfq', 'brar_br_bfq', 'brar_br_hfq', 'brar_br_qfq', 'cci_bfq', 'cci_hfq', 'cci_qfq', 'cr_bfq', 'cr_hfq', 'cr_qfq', 'dfma_dif_bfq', 'dfma_dif_hfq', 'dfma_dif_qfq', 'dfma_difma_bfq', 'dfma_difma_hfq', 'dfma_difma_qfq', 'dmi_adx_bfq', 'dmi_adx_hfq', 'dmi_adx_qfq', 'dmi_adxr_bfq', 'dmi_adxr_hfq', 'dmi_adxr_qfq', 'dmi_mdi_bfq', 'dmi_mdi_hfq', 'dmi_mdi_qfq', 'dmi_pdi_bfq', 'dmi_pdi_hfq', 'dmi_pdi_qfq', 'downdays', 'updays', 'dpo_bfq', 'dpo_hfq', 'dpo_qfq', 'madpo_bfq', 'madpo_hfq', 'madpo_qfq', 'ema_bfq_10', 'ema_bfq_20', 'ema_bfq_250', 'ema_bfq_30', 'ema_bfq_5', 'ema_bfq_60', 'ema_bfq_90', 'ema_hfq_10', 'ema_hfq_20', 'ema_hfq_250', 'ema_hfq_30', 'ema_hfq_5', 'ema_hfq_60', 'ema_hfq_90', 'ema_qfq_10', 'ema_qfq_20', 'ema_qfq_250', 'ema_qfq_30', 'ema_qfq_5', 'ema_qfq_60', 'ema_qfq_90', 'emv_bfq', 'emv_hfq', 'emv_qfq', 'maemv_bfq', 'maemv_hfq', 'maemv_qfq', 'expma_12_bfq', 'expma_12_hfq', 'expma_12_qfq', 'expma_50_bfq', 'expma_50_hfq', 'expma_50_qfq', 'kdj_bfq', 'kdj_hfq', 'kdj_qfq', 'kdj_d_bfq', 'kdj_d_hfq', 'kdj_d_qfq', 'kdj_k_bfq', 'kdj_k_hfq', 'kdj_k_qfq', 'ktn_down_bfq', 'ktn_down_hfq', 'ktn_down_qfq', 'ktn_mid_bfq', 'ktn_mid_hfq', 'ktn_mid_qfq', 'ktn_upper_bfq', 'ktn_upper_hfq', 'ktn_upper_qfq', 'lowdays', 'topdays', 'ma_bfq_10', 'ma_bfq_20', 'ma_bfq_250', 'ma_bfq_30', 'ma_bfq_5', 'ma_bfq_60', 'ma_bfq_90', 'ma_hfq_10', 'ma_hfq_20', 'ma_hfq_250', 'ma_hfq_30', 'ma_hfq_5', 'ma_hfq_60', 'ma_hfq_90', 'ma_qfq_10', 'ma_qfq_20', 'ma_qfq_250', 'ma_qfq_30', 'ma_qfq_5', 'ma_qfq_60', 'ma_qfq_90', 'macd_bfq', 'macd_hfq', 'macd_qfq', 'macd_dea_bfq', 'macd_dea_hfq', 'macd_dea_qfq', 'macd_dif_bfq', 'macd_dif_hfq', 'macd_dif_qfq', 'mass_bfq', 'mass_hfq', 'mass_qfq', 'ma_mass_bfq', 'ma_mass_hfq', 'ma_mass_qfq', 'mfi_bfq', 'mfi_hfq', 'mfi_qfq', 'mtm_bfq', 'mtm_hfq', 'mtm_qfq', 'mtmma_bfq', 'mtmma_hfq', 'mtmma_qfq', 'obv_bfq', 'obv_hfq', 'obv_qfq', 'psy_bfq', 'psy_hfq', 'psy_qfq', 'psyma_bfq', 'psyma_hfq', 'psyma_qfq', 'roc_bfq', 'roc_hfq', 'roc_qfq', 'maroc_bfq', 'maroc_hfq', 'maroc_qfq', 'rsi_bfq_12', 'rsi_bfq_24', 'rsi_bfq_6', 'rsi_hfq_12', 'rsi_hfq_24', 'rsi_hfq_6', 'rsi_qfq_12', 'rsi_qfq_24', 'rsi_qfq_6', 'taq_down_bfq', 'taq_down_hfq', 'taq_down_qfq', 'taq_mid_bfq', 'taq_mid_hfq', 'taq_mid_qfq', 'taq_up_bfq', 'taq_up_hfq', 'taq_up_qfq', 'trix_bfq', 'trix_hfq', 'trix_qfq', 'trma_bfq', 'trma_hfq', 'trma_qfq', 'vr_bfq', 'vr_hfq', 'vr_qfq', 'wr_bfq', 'wr_hfq', 'wr_qfq', 'wr1_bfq', 'wr1_hfq', 'wr1_qfq', 'xsii_td1_bfq', 'xsii_td1_hfq', 'xsii_td1_qfq', 'xsii_td2_bfq', 'xsii_td2_hfq', 'xsii_td2_qfq', 'xsii_td3_bfq', 'xsii_td3_hfq', 'xsii_td3_qfq', 'xsii_td4_bfq', 'xsii_td4_hfq', 'xsii_td4_qfq'],
    },
    'margin': {
        'model': MarginSummary,
        'fields': ['trade_date', 'exchange_id', 'rzye', 'rzmre', 'rzche', 'rqye', 'rqmcl', 'rzrqye', 'rqyl'],
    },
    'pledge_detail': {
        'model': PledgeDetail,
        'fields': ['ts_code', 'ann_date', 'holder_name', 'pledge_amount', 'start_date', 'end_date', 'is_release', 'release_date', 'pledgor', 'holding_amount', 'pledged_amount', 'p_total_ratio', 'h_total_ratio', 'is_buyback'],
    },
    'forecast': {
        'model': PerformanceForecast,
        'fields': ['ts_code', 'ann_date', 'end_date', 'type', 'p_change_min', 'p_change_max', 'net_profit_min', 'net_profit_max', 'last_parent_net', 'first_ann_date', 'summary', 'change_reason'],
    },
    'express': {
        'model': PerformanceExpress,
        'fields': ['ts_code', 'ann_date', 'end_date', 'revenue', 'operate_profit', 'total_profit', 'n_income', 'total_assets', 'total_hldr_eqy_exc_min_int', 'diluted_eps', 'diluted_roe', 'yoy_net_profit', 'bps', 'yoy_sales', 'yoy_op', 'yoy_tp', 'yoy_dedu_np', 'yoy_eps', 'yoy_roe', 'growth_assets', 'yoy_equity', 'growth_bps', 'or_last_year', 'op_last_year', 'tp_last_year', 'np_last_year', 'eps_last_year', 'open_net_assets', 'open_bps', 'perf_summary', 'is_audit', 'remark'],
    },
    'block_trade': {
        'model': BlockTrade,
        'fields': ['ts_code', 'trade_date', 'price', 'vol', 'amount', 'buyer', 'seller'],
    },
    'top_list': {
        'model': TopList,
        'fields': [
            'trade_date', 'ts_code', 'name', 'close', 'pct_change', 'turnover_rate',
            'amount', 'l_sell', 'l_buy', 'l_amount', 'net_amount', 'net_rate',
            'amount_rate', 'float_values', 'reason',
        ],
    },
    'top_inst': {
        'model': TopInst,
        'fields': [
            'trade_date', 'ts_code', 'exalter', 'buy', 'buy_rate', 'sell', 'sell_rate',
            'net_buy', 'side', 'reason',
        ],
    },
    'dividend': {
        'model': Dividend,
        'fields': ['ts_code', 'end_date', 'ann_date', 'div_proc', 'stk_div', 'stk_bo_rate', 'stk_co_rate', 'cash_div', 'cash_div_tax', 'record_date', 'ex_date', 'pay_date', 'div_listdate', 'imp_ann_date', 'base_date', 'base_share'],
    },
    'repurchase': {
        'model': Repurchase,
        'fields': ['ts_code', 'ann_date', 'end_date', 'proc', 'exp_date', 'vol', 'amount', 'high_limit', 'low_limit'],
    },
}


def catalog_for(name):
    return TUSHARE_CATALOG[name]


def model_for(name):
    return MODEL_CONFIG[name]['model']


def fields_for(name):
    return MODEL_CONFIG[name]['fields']


def get_job(name):
    return SyncJob.objects.filter(name=name).first()
